name: Build Local Container & Save

on:
  workflow_dispatch:
    inputs:
      docker_user:
        description: 'docker image owner'
        default: 'pknw1'
      docker_image:
        description: 'docker image and tag'
        default: 'maverick'
      docker_tag:
        description: 'docker image tag'
        default: 'latest'
      hostname:
        description: 'docker container hostname'
        default: 'mav.pknw1.co.uk'
      hostport:
        description: 'internal container http port'
        default: '80'
      deploy_stack:
        description: 'Components to include'
        type: choice
        options:
          - simple
          - proxied
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: create string
        run: |
          TIMESTAMP=$(date)
          echo "![](https://www.pknw1.co.uk/assets/img/pknw1logo-white.png)"  >> $GITHUB_STEP_SUMMARY
          echo "## ${{ github.fullName }} build"  >> $GITHUB_STEP_SUMMARY
          echo "started at "${TIMESTAMP}  >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
      - uses: actions/checkout@v3
      - run: |
          cat << EOF >> testfile
          pk
          pk2
          pk3
          EOF
          
